# INFO 212: Data Science Programming 1
## CCI at Drexel University


## Week 8 Lab : Cleaning and Aggregation

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

## Exercise 1

1. Download and upload the nba-2016.csv. Create a DataFrame df from the data set. Show information of the DataFrame.

In [5]:
df = pd.read_csv('/content/drive/MyDrive/info212/nba-2016(1).csv')
df.head()

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes
0,Tue Oct 27 2015,8:00p,Cleveland Cavaliers,95,Chicago Bulls,97,Box Score,NaN,21957,NaN
1,Tue Oct 27 2015,8:00p,Detroit Pistons,106,Atlanta Hawks,94,Box Score,NaN,19187,NaN
2,Tue Oct 27 2015,10:30p,New Orleans Pelicans,95,Golden State Warriors,111,Box Score,NaN,19596,NaN
3,Wed Oct 28 2015,7:00p,Washington Wizards,88,Orlando Magic,87,Box Score,NaN,18846,NaN
4,Wed Oct 28 2015,7:30p,Philadelphia 76ers,95,Boston Celtics,112,Box Score,NaN,18624,NaN

2. Does the dataset have mssing values? Compute the percentage of missing values overall.

In [24]:
# Check if the dataset has missing values
has_missing_values = df.isnull().values.any()

# Calculate the percentage of missing values
missing_percentage = (df.isnull().sum().sum() / df.size) * 100

# Output the results
print(f"Does the dataset have missing values? {'Yes' if has_missing_values else 'No'}")
print(f"Percentage of missing values overall: {missing_percentage:.2f}%")

Does the dataset have missing values? Yes
Percentage of missing values overall: 19.36%

3. List the number and percentage of missing values for each row.

In [25]:
# Calculate the number of missing values for each row
row_missing_count = df.isnull().sum(axis=1)

# Calculate the percentage of missing values for each row
row_missing_percentage = (row_missing_count / df.shape[1]) * 100

# Combine the results into a DataFrame
missing_values_per_row = pd.DataFrame({
    'Number of Missing Values': row_missing_count,
    'Percentage of Missing Values': row_missing_percentage
})

# Display the results
print(missing_values_per_row)

      Number of Missing Values  Percentage of Missing Values
0                            2                          20.0
1                            2                          20.0
2                            2                          20.0
3                            2                          20.0
4                            2                          20.0
...                        ...                           ...
1311                         2                          20.0
1312                         2                          20.0
1313                         2                          20.0
1314                         2                          20.0
1315                         2                          20.0

[1316 rows x 2 columns]

4. List the number and percentage of missing values for each column.

In [26]:
# Calculate the number of missing values for each column
column_missing_count = df.isnull().sum()

# Calculate the percentage of missing values for each column
column_missing_percentage = (column_missing_count / df.shape[0]) * 100

# Combine the results into a DataFrame
missing_values_per_column = pd.DataFrame({
    'Number of Missing Values': column_missing_count,
    'Percentage of Missing Values': column_missing_percentage
})

# Display the results
print(missing_values_per_column)

                 Number of Missing Values  Percentage of Missing Values
Date                                    0                      0.000000
Start (ET)                              0                      0.000000
Visitor/Neutral                         0                      0.000000
PTS                                     0                      0.000000
Home/Neutral                            0                      0.000000
PTS.1                                   0                      0.000000
Unnamed: 6                              0                      0.000000
Unnamed: 7                           1234                     93.768997
Attend.                                 0                      0.000000
Notes                                1314                     99.848024

5. If there are missing values for a column, forward fill the missing values. Does it make sense to forward or backward fill the missing values for each row?

In [27]:
# Forward-fill the missing values for each column
data_filled = df.ffill(axis=0)

# Output the result (if needed)
print(data_filled)

                 Date Start (ET)        Visitor/Neutral  PTS  \
0     Tue Oct 27 2015      8:00p    Cleveland Cavaliers   95
1     Tue Oct 27 2015      8:00p        Detroit Pistons  106
2     Tue Oct 27 2015     10:30p   New Orleans Pelicans   95
3     Wed Oct 28 2015      7:00p     Washington Wizards   88
4     Wed Oct 28 2015      7:30p     Philadelphia 76ers   95
...               ...        ...                    ...  ...
1311   Wed Jun 8 2016      9:00p  Golden State Warriors   90
1312  Fri Jun 10 2016      9:00p  Golden State Warriors  108
1313  Mon Jun 13 2016      9:00p    Cleveland Cavaliers  112
1314  Thu Jun 16 2016      9:00p  Golden State Warriors  101
1315  Sun Jun 19 2016      8:00p    Cleveland Cavaliers   93

               Home/Neutral  PTS.1 Unnamed: 6 Unnamed: 7  Attend.  \
0             Chicago Bulls     97  Box Score        NaN    21957
1             Atlanta Hawks     94  Box Score        NaN    19187
2     Golden State Warriors    111  Box Score        NaN    19596
3             Orlando Magic     87  Box Score        NaN    18846
4            Boston Celtics    112  Box Score        NaN    18624
...                     ...    ...        ...        ...      ...
1311    Cleveland Cavaliers    120  Box Score         OT    20562
1312    Cleveland Cavaliers     97  Box Score         OT    20562
1313  Golden State Warriors     97  Box Score         OT    19596
1314    Cleveland Cavaliers    115  Box Score         OT    20562
1315  Golden State Warriors     89  Box Score         OT    19596

                  Notes
0                   NaN
1                   NaN
2                   NaN
3                   NaN
4                   NaN
...                 ...
1311  at London England
1312  at London England
1313  at London England
1314  at London England
1315  at London England

[1316 rows x 10 columns]

Row-wise filling (axis=1) rarely makes sense unless the rows represent a sequence or context where adjacent cells in a row are interdependent.
Typically, rows are independent observations, so filling should focus on columns

6. Group by the Visitor/Neutral teams. Compute the aveage points (PTS) for each team playing as visiting team.

In [28]:
# Group by the "Visitor/Neutral" column and compute the average points (PTS) for each visiting team
average_points_by_team = df.groupby('Visitor/Neutral')['PTS'].mean()

# Display the result
print(average_points_by_team)

Visitor/Neutral
Atlanta Hawks             101.717391
Boston Celtics            104.022727
Brooklyn Nets              98.365854
Charlotte Hornets         100.266667
Chicago Bulls             101.463415
Cleveland Cavaliers       101.384615
Dallas Mavericks           99.318182
Denver Nuggets            100.121951
Detroit Pistons            98.720930
Golden State Warriors     112.098039
Houston Rockets           105.568182
Indiana Pacers            100.622222
Los Angeles Clippers      103.340909
Los Angeles Lakers         97.878049
Memphis Grizzlies          95.162791
Miami Heat                 96.000000
Milwaukee Bucks            97.243902
Minnesota Timberwolves    103.317073
New Orleans Pelicans       99.512195
New York Knicks            97.878049
Oklahoma City Thunder     109.600000
Orlando Magic              99.609756
Philadelphia 76ers         96.756098
Phoenix Suns               98.634146
Portland Trail Blazers    102.170213
Sacramento Kings          105.609756
San Antonio Spurs         101.891304
Toronto Raptors            98.200000
Utah Jazz                  96.804878
Washington Wizards        102.121951
Name: PTS, dtype: float64

7. Add a new column 'VisitorWon' which has True for the Visiting team won and False otherwise.

In [30]:
# Add a new column 'VisitorWon' where True indicates the visiting team won
df['VisitorWon'] = df['PTS'] > df['PTS.1']

df.head()

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes,VisitorWon
0,Tue Oct 27 2015,8:00p,Cleveland Cavaliers,95,Chicago Bulls,97,Box Score,NaN,21957,NaN,False
1,Tue Oct 27 2015,8:00p,Detroit Pistons,106,Atlanta Hawks,94,Box Score,NaN,19187,NaN,True
2,Tue Oct 27 2015,10:30p,New Orleans Pelicans,95,Golden State Warriors,111,Box Score,NaN,19596,NaN,False
3,Wed Oct 28 2015,7:00p,Washington Wizards,88,Orlando Magic,87,Box Score,NaN,18846,NaN,True
4,Wed Oct 28 2015,7:30p,Philadelphia 76ers,95,Boston Celtics,112,Box Score,NaN,18624,NaN,False

8. Compute the rate of VisitorWon for each team playing away during the 2016 season, in descending order.

In [32]:
#the rate of VisitorWon for each team for the away during 2016 season
visitor_wins_by_team = df.groupby('Visitor/Neutral')['VisitorWon'].mean().sort_values(ascending=False)


visitor_wins_by_team

Visitor/Neutral
Golden State Warriors     0.745098
San Antonio Spurs         0.652174
Cleveland Cavaliers       0.596154
Oklahoma City Thunder     0.560000
Los Angeles Clippers      0.545455
Toronto Raptors           0.520000
Atlanta Hawks             0.478261
Washington Wizards        0.463415
Miami Heat                0.458333
Boston Celtics            0.454545
Dallas Mavericks          0.454545
Indiana Pacers            0.444444
Charlotte Hornets         0.422222
Detroit Pistons           0.418605
Houston Rockets           0.409091
Chicago Bulls             0.390244
Utah Jazz                 0.390244
Memphis Grizzlies         0.372093
Minnesota Timberwolves    0.365854
Denver Nuggets            0.365854
Sacramento Kings          0.365854
Portland Trail Blazers    0.361702
New York Knicks           0.341463
Orlando Magic             0.292683
Milwaukee Bucks           0.243902
New Orleans Pelicans      0.219512
Phoenix Suns              0.219512
Brooklyn Nets             0.170732
Los Angeles Lakers        0.121951
Philadelphia 76ers        0.073171
Name: VisitorWon, dtype: float64

9. Define a function 'top' that returns the top two rows based on a given col value. List each team's top 2 winning visiting games in which the team got top 2 highest points. Order the results by team names.

In [34]:
# Define the 'top' function
def top(group, col, n=2):
    """Return the top n rows in the group based on the given column."""
    return group.nlargest(n, col)

# Filter for games where the visiting team won
winning_games = df[df['VisitorWon']]

# Group by visiting teams and apply the 'top' function
top_winning_games = (
    winning_games.groupby('Visitor/Neutral', group_keys=False)
    .apply(top, col='PTS', n=2)
)

# Sort the results by team names
top_winning_games = top_winning_games.sort_values(by='Visitor/Neutral')

# Display the results
top_winning_games

<ipython-input-34-d97db5109d35>:11: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  winning_games.groupby('Visitor/Neutral', group_keys=False)

,Date,Start (ET),Visitor/Neutral,PTS,Home/Neutral,PTS.1,Unnamed: 6,Unnamed: 7,Attend.,Notes,VisitorWon
535,Thu Jan 7 2016,7:00p,Atlanta Hawks,126,Philadelphia 76ers,98,Box Score,NaN,12611,NaN,True
734,Wed Feb 3 2016,7:00p,Atlanta Hawks,124,Philadelphia 76ers,86,Box Score,NaN,10429,NaN,True
824,Sun Feb 21 2016,5:00p,Boston Celtics,121,Denver Nuggets,101,Box Score,NaN,16065,NaN,True
1039,Sun Mar 20 2016,6:00p,Boston Celtics,120,Philadelphia 76ers,105,Box Score,NaN,15103,NaN,True
919,Fri Mar 4 2016,9:00p,Brooklyn Nets,121,Denver Nuggets,120,Box Score,OT,14163,NaN,True
857,Thu Feb 25 2016,9:00p,Brooklyn Nets,116,Phoenix Suns,106,Box Score,NaN,16145,NaN,True
672,Mon Jan 25 2016,10:00p,Charlotte Hornets,129,Sacramento Kings,128,Box Score,2OT,16991,NaN,True
337,Fri Dec 11 2015,8:00p,Charlotte Hornets,123,Memphis Grizzlies,99,Box Score,NaN,17111,NaN,True
1207,Mon Apr 11 2016,8:00p,Chicago Bulls,121,New Orleans Pelicans,116,Box Score,NaN,16867,NaN,True
5,Wed Oct 28 2015,7:30p,Chicago Bulls,115,Brooklyn Nets,100,Box Score,NaN,17732,NaN,True
543,Fri Jan 8 2016,8:00p,Cleveland Cavaliers,125,Minnesota Timberwolves,99,Box Score,NaN,16768,NaN,True
526,Wed Jan 6 2016,7:00p,Cleveland Cavaliers,121,Washington Wizards,115,Box Score,NaN,20356,NaN,True
301,Sun Dec 6 2015,6:00p,Dallas Mavericks,116,Washington Wizards,104,Box Score,NaN,16394,NaN,True
427,Wed Dec 23 2015,7:30p,Dallas Mavericks,119,Brooklyn Nets,118,Box Score,OT,15994,NaN,True
58,Tue Nov 3 2015,10:30p,Denver Nuggets,120,Los Angeles Lakers,109,Box Score,NaN,18997,NaN,True
691,Thu Jan 28 2016,7:00p,Denver Nuggets,117,Washington Wizards,113,Box Score,NaN,15146,NaN,True
389,Fri Dec 18 2015,8:00p,Detroit Pistons,147,Chicago Bulls,144,Box Score,4OT,21534,NaN,True
974,Sat Mar 12 2016,7:00p,Detroit Pistons,125,Philadelphia 76ers,111,Box Score,NaN,16087,NaN,True
235,Fri Nov 27 2015,9:30p,Golden State Warriors,135,Phoenix Suns,116,Box Score,NaN,18055,NaN,True
34,Sat Oct 31 2015,7:30p,Golden State Warriors,134,New Orleans Pelicans,120,Box Score,NaN,18406,NaN,True
1206,Mon Apr 11 2016,8:00p,Houston Rockets,129,Minnesota Timberwolves,105,Box Score,NaN,14983,NaN,True
858,Thu Feb 25 2016,10:30p,Houston Rockets,119,Portland Trail Blazers,105,Box Score,NaN,19393,NaN,True
208,Tue Nov 24 2015,7:00p,Indiana Pacers,123,Washington Wizards,106,Box Score,NaN,15486,NaN,True
1137,Sat Apr 2 2016,7:30p,Indiana Pacers,115,Philadelphia 76ers,102,Box Score,NaN,19213,NaN,True
473,Wed Dec 30 2015,7:00p,Los Angeles Clippers,122,Charlotte Hornets,117,Box Score,NaN,19145,NaN,True
1008,Wed Mar 16 2016,9:30p,Los Angeles Clippers,122,Houston Rockets,106,Box Score,NaN,18304,NaN,True
475,Wed Dec 30 2015,7:30p,Los Angeles Lakers,112,Boston Celtics,104,Box Score,NaN,18624,NaN,True
421,Tue Dec 22 2015,9:00p,Los Angeles Lakers,111,Denver Nuggets,107,Box Score,NaN,19124,NaN,True
265,Tue Dec 1 2015,8:00p,Memphis Grizzlies,113,New Orleans Pelicans,104,Box Score,NaN,16020,NaN,True
145,Sun Nov 15 2015,3:30p,Memphis Grizzlies,114,Minnesota Timberwolves,106,Box Score,NaN,12086,NaN,True
965,Fri Mar 11 2016,8:00p,Miami Heat,118,Chicago Bulls,96,Box Score,NaN,22067,NaN,True
807,Fri Feb 19 2016,8:00p,Miami Heat,115,Atlanta Hawks,111,Box Score,NaN,19043,NaN,True
484,Thu Dec 31 2015,6:00p,Milwaukee Bucks,120,Indiana Pacers,116,Box Score,NaN,16348,NaN,True
818,Sat Feb 20 2016,7:30p,Milwaukee Bucks,117,Atlanta Hawks,109,Box Score,2OT,18653,NaN,True
1072,Fri Mar 25 2016,7:00p,Minnesota Timberwolves,132,Washington Wizards,129,Box Score,2OT,20356,NaN,True
1162,Tue Apr 5 2016,10:30p,Minnesota Timberwolves,124,Golden State Warriors,117,Box Score,OT,19596,NaN,True
408,Sun Dec 20 2015,8:00p,New Orleans Pelicans,130,Denver Nuggets,125,Box Score,NaN,13857,NaN,True
1009,Wed Mar 16 2016,10:00p,New Orleans Pelicans,123,Sacramento Kings,108,Box Score,NaN,17086,NaN,True
954,Wed Mar 9 2016,9:00p,New York Knicks,128,Phoenix Suns,97,Box Score,NaN,17105,NaN,True
9,Wed Oct 28 2015,8:00p,New York Knicks,122,Milwaukee Bucks,97,Box Score,NaN,18717,NaN,True
22,Fri Oct 30 2015,7:00p,Oklahoma City Thunder,139,Orlando Magic,136,Box Score,2OT,18846,NaN,True
888,Mon Feb 29 2016,10:00p,Oklahoma City Thunder,131,Sacramento Kings,116,Box Score,NaN,17317,NaN,True
778,Mon Feb 8 2016,8:00p,Orlando Magic,117,Atlanta Hawks,110,Box Score,OT,13057,NaN,True
839,Tue Feb 23 2016,7:00p,Orlando Magic,124,Philadelphia 76ers,115,Box Score,NaN,13745,NaN,True
482,Wed Dec 30 2015,10:00p,Philadelphia 76ers,110,Sacramento Kings,105,Box Score,NaN,17317,NaN,True
450,Sat Dec 26 2015,9:00p,Philadelphia 76ers,111,Phoenix Suns,104,Box Score,NaN,17548,NaN,True
1173,Thu Apr 7 2016,8:00p,Phoenix Suns,124,Houston Rockets,115,Box Score,NaN,18227,NaN,True
1187,Sat Apr 9 2016,7:00p,Phoenix Suns,121,New Orleans Pelicans,100,Box Score,NaN,16932,NaN,True
1024,Fri Mar 18 2016,8:00p,Portland Trail Blazers,117,New Orleans Pelicans,112,Box Score,NaN,17263,NaN,True
595,Fri Jan 15 2016,7:30p,Portland Trail Blazers,116,Brooklyn Nets,104,Box Score,NaN,14749,NaN,True
220,Wed Nov 25 2015,8:00p,Sacramento Kings,129,Milwaukee Bucks,118,Box Score,NaN,14120,NaN,True
516,Mon Jan 4 2016,8:00p,Sacramento Kings,116,Oklahoma City Thunder,104,Box Score,NaN,18203,NaN,True
515,Mon Jan 4 2016,8:00p,San Antonio Spurs,123,Milwaukee Bucks,98,Box Score,NaN,14718,NaN,True
304,Mon Dec 7 2015,7:00p,San Antonio Spurs,119,Philadelphia 76ers,68,Box Score,NaN,14449,NaN,True
834,Mon Feb 22 2016,7:30p,Toronto Raptors,122,New York Knicks,95,Box Score,NaN,19812,NaN,True
114,Wed Nov 11 2015,7:00p,Toronto Raptors,119,Philadelphia 76ers,103,Box Score,NaN,12744,NaN,True
785,Tue Feb 9 2016,8:30p,Utah Jazz,121,Dallas Mavericks,119,Box Score,OT,19394,NaN,True
646,Fri Jan 22 2016,7:30p,Utah Jazz,108,Brooklyn Nets,86,Box Score,NaN,12809,NaN,True
709,Sat Jan 30 2016,8:00p,Washington Wizards,123,Houston Rockets,122,Box Score,NaN,18320,NaN,True
1205,Mon Apr 11 2016,7:30p,Washington Wizards,120,Brooklyn Nets,111,Box Score,NaN,14653,NaN,True

## Exercise 2

1. Download and upload the Cleaned_Laptop_data.csv. Create a DataFrame df from the data set. Show information of the DataFrame.

In [35]:
df = pd.read_csv('/content/drive/MyDrive/info212/Cleaned_Laptop_data(1).csv')
df.head()

,brand,model,processor_brand,processor_name,processor_gnrtn,ram_gb,ram_type,ssd,hdd,os,...,display_size,warranty,Touchscreen,msoffice,latest_price,old_price,discount,star_rating,ratings,reviews
0,ASUS,Celeron,Intel,Celeron Dual,Missing,4,DDR4,0,1024,Windows,...,15.6,1,No,No,23990,26990,11,3.8,15279,1947
1,ASUS,VivoBook,Intel,Core i3,10th,8,DDR4,512,0,Windows,...,15.6,1,No,No,37990,50990,25,4.3,990,108
2,ASUS,Vivobook,Intel,Core i3,10th,8,DDR4,0,1024,Windows,...,14.1,1,No,No,32890,46990,30,3.9,28,4
3,HP,Core,Intel,Core i3,11th,8,DDR4,512,0,Windows,...,15.6,1,No,Yes,42990,57330,25,4.4,158,18
4,HP,Core,Intel,Core i5,11th,8,DDR4,512,0,Windows,...,15.6,0,No,No,54990,70171,21,4.2,116,15

2. Forward fill missing values for each column. Ensure there is no missing value after the filling.

In [37]:
# Forward fill missing values for each column
df_filled = df.ffill(axis=0)

# Check if there are any missing values remaining
missing_values_remaining = df_filled.isnull().values.any()

# Print the result
print(f"Are there any missing values left? {'Yes' if missing_values_remaining else 'No'}")

Are there any missing values left? No

3. Create a pivot table containing the means of latest_price and ratings indexed by brand, model, and os. Put os on columns and also compute the margins.

In [40]:
# Create a pivot table with means of 'latest_price' and 'ratings'
pivot_table = pd.pivot_table(
    df,
    values=['latest_price', 'ratings'],
    index=['brand', 'model'],
    columns='os',
    aggfunc='mean',
    margins=True
)

# Display the pivot table
pivot_table.head()

                    latest_price                                    \
os                           Mac   Missing  Windows            All
brand     model
ALIENWARE Core               NaN  257365.0      NaN  257365.000000
APPLE     2020     107740.000000       NaN      NaN  107740.000000
          2021     236156.666667       NaN      NaN  236156.666667
          MacBook  140640.000000       NaN      NaN  140640.000000
ASUS      AMD                NaN       NaN  80990.0   80990.000000

                       ratings
os                         Mac Missing Windows          All
brand     model
ALIENWARE Core             NaN    10.0     NaN    10.000000
APPLE     2020     2143.250000     NaN     NaN  2143.250000
          2021       35.500000     NaN     NaN    35.500000
          MacBook  1175.142857     NaN     NaN  1175.142857
ASUS      AMD              NaN     NaN     0.0     0.000000

4. Using pd.crosstab() to compute the numbers of laptops by brand and os.

In [43]:
# Compute the number of laptops by brand and os
crosstab_result = pd.crosstab(df['brand'], df['os'])

# Display the result
crosstab_result

os         Mac  Missing  Windows
brand
ALIENWARE    0        4        0
APPLE       28        0        0
ASUS         0       16      238
Avita        0        0       18
DELL         0        5      149
HP           0       14      128
Infinix      0        0        4
LG           0        0        5
Lenovo       0       11      137
MICROSOFT    0        0        3
MSI          0        8       44
Mi           0        0        2
Nokia        0        0        4
RedmiBook    0        0        3
SAMSUNG      0        0        1
Smartron     0        0        3
Vaio         0        0        5
acer         0       11       47
iball        0        0        1
lenovo       0        3        0
realme       0        0        4