# INFO 212: Data Science Programming 1
## CCI at Drexel University


## Week 3: Lab: Numpy and Pandas

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

## What to do:
- Answer each question individually.
- Comment on each single statement.
- Each missing comment will be penalized by 1 point.
- Verify the code by showing meaningful results.

import packages

In [2]:
import numpy as np
import pandas as pd
import random
import math
import matplotlib.pyplot as plt

## Exercise 1:

Create 3 lists, `ls1`, `ls2`, and `ls3`, with the following values:
- `ls1` contains 10 random decimal numbers in the range of (0.00, 150.00), each of which with 2-digit precision.
- `ls2` contains 10 random integers in the range of (1, 500).
- `ls3` contains 10 random decimal numbers in the range of (0.05, 0.90), each of which with 2-digit precision and the last digit rounded to the nearest 0 or 5.

Show the content of the lists.

In [9]:
ls1 = np.random.uniform(0.00, 150.00, 10)
ls2 = np.random.randint(1, 500, 10)

# Generate 10 random decimal numbers between 0.05 and 0.90, multiply by 20 to shift the decimal,
# round to the nearest integer (ensuring last digit is 0 or 5), then divide by 20 to scale back down,
# and round the result to 2 decimal places for precision.
ls3 = ls3 = np.round(np.round(np.random.uniform(0.05, 0.90, 10) * 20) / 20, 2)

print(ls1)
print(ls2)
print(ls3)

[139.21803867   0.21381192 107.08170526 128.85306373  17.9011042
  65.92907512  73.67916425  18.53748928 122.45547474 125.4096663 ]
[198 236 330 438 483 375 436  34 163  62]
[0.8  0.15 0.25 0.2  0.1  0.6  0.3  0.85 0.25 0.65]

## Exercise 2:
- Use the 3 lists as 3 columns to create a numpy array `arr` which uses `ls1` as the first column, `ls2` as the second column, and `ls3` as the third column.
- Show the content and shape of the array.

In [12]:
# Stack the three lists as columns to form a 2D numpy array
arr = np.column_stack((ls1, ls2, ls3))
print(arr)

[[1.39218039e+02 1.98000000e+02 8.00000000e-01]
 [2.13811924e-01 2.36000000e+02 1.50000000e-01]
 [1.07081705e+02 3.30000000e+02 2.50000000e-01]
 [1.28853064e+02 4.38000000e+02 2.00000000e-01]
 [1.79011042e+01 4.83000000e+02 1.00000000e-01]
 [6.59290751e+01 3.75000000e+02 6.00000000e-01]
 [7.36791642e+01 4.36000000e+02 3.00000000e-01]
 [1.85374893e+01 3.40000000e+01 8.50000000e-01]
 [1.22455475e+02 1.63000000e+02 2.50000000e-01]
 [1.25409666e+02 6.20000000e+01 6.50000000e-01]]

## Exercise 3:
- For the third column of `arr`, compute a boolean array indicating whether the value is between [0.20, 0.50].
- Use the boolean array to extract the rows of `arr` such as the values of the third column are between [0.20, 0.50].

In [13]:
third_column = arr[:, 2]  # Extract the third column of the array
boolean_array = (third_column >= 0.20) & (third_column <= 0.50)  # Create a boolean array based on the condition
extracted_rows = arr[boolean_array]  # Use the boolean array to extract the rows that meet the condition
print(extracted_rows)

[[1.07081705e+02 3.30000000e+02 2.50000000e-01]
 [1.28853064e+02 4.38000000e+02 2.00000000e-01]
 [7.36791642e+01 4.36000000e+02 3.00000000e-01]
 [1.22455475e+02 1.63000000e+02 2.50000000e-01]]

## Exercise 4:

Use `ls1`, `ls2`, and `ls3` as the three columns to create a Pandas DataFrame `items`. Assign the column names as `['price', 'quantity', 'discount']`.

## Exercise 5:

Show the shape, columns, and summary statistics of the DataFrame `items`.

In [18]:
# Creating a simple Pandas DataFrame using ls1, ls2, and ls3 as columns
items = pd.DataFrame({'price': ls1, 'quantity' : ls2, 'discount' : ls3})
print(items)

        price  quantity  discount
0  139.218039       198      0.80
1    0.213812       236      0.15
2  107.081705       330      0.25
3  128.853064       438      0.20
4   17.901104       483      0.10
5   65.929075       375      0.60
6   73.679164       436      0.30
7   18.537489        34      0.85
8  122.455475       163      0.25
9  125.409666        62      0.65

## Exercise 6:

Create a list of 10 strings as item names (meaningful names). Assign the names to the index of the DataFrame `items`. Show the final DataFrame.

In [17]:
#Random names and it is indexed to the items data frame with the index function
item_names = ['Laptop', 'Keyboard', 'Mouse', 'Monitor', 'Printer', 'Tablet', 'Charger', 'Headset', 'Webcam', 'Router']
items.index = item_names
print(items)

               price  quantity  discount
Laptop    139.218039       198      0.80
Keyboard    0.213812       236      0.15
Mouse     107.081705       330      0.25
Monitor   128.853064       438      0.20
Printer    17.901104       483      0.10
Tablet     65.929075       375      0.60
Charger    73.679164       436      0.30
Headset    18.537489        34      0.85
Webcam    122.455475       163      0.25
Router    125.409666        62      0.65